In [9]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [10]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서', np.nan]

In [15]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 2, 5, 6, 4, 3, 3, 1])

In [12]:
encoder.classes_

array(['TV', 'nan', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U32')

In [16]:
encoder.inverse_transform([2,4,1,3,6])

array(['냉장고', '선풍기', 'nan', '믹서', '컴퓨터'], dtype='<U32')

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']
items = np.array(items).reshape(-1,1)
items.shape

(7, 1)

In [33]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)
oh_labels

<7x6 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [34]:
import pandas as pd

In [35]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']
pd.get_dummies(items).values

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)

In [1]:
# 5/9 화요일

In [3]:
from sklearn.datasets import load_iris
import pandas as pd

In [4]:
iris = load_iris()

In [6]:
iris_df = pd.DataFrame(data=iris.data, 
             columns=iris.feature_names)

In [13]:
iris_df.mean() # 평균값

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [14]:
iris_df.var() # 분산

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [15]:
iris_df.std() # 표준편차

sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64

In [16]:
iris_df.min()

sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

In [17]:
iris_df.max()

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()
iris_scaled = scaler.fit_transform(iris_df)
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [21]:
iris_df_scaled = pd.DataFrame(data=iris_scaled, 
                                   columns=iris.feature_names)

In [22]:
iris_df_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [23]:
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [24]:
iris_df_scaled.std()

sepal length (cm)    1.00335
sepal width (cm)     1.00335
petal length (cm)    1.00335
petal width (cm)     1.00335
dtype: float64

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
scaler = MinMaxScaler()
iris_scaled = scaler.fit_transform(iris_df)

In [30]:
iris_df_scaled = pd.DataFrame(data=iris_scaled, 
                              columns=iris.feature_names)

In [31]:
iris_df_scaled.min()

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

In [32]:
iris_df_scaled.max()

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

In [33]:
import numpy as np

In [40]:
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)
train_array, test_array

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]))

In [44]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
train_scaled.reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [43]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)
test_scaled.reshape(-1)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [46]:
scaler.fit(train_array)
test_scaled = scaler.transform(test_array)
test_scaled.reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])